# Generated by Django 4.2 on 2023-04-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('shopname', models.CharField(max_length=25)),
            ],
        ),
    ]
