# Generated by Django 4.2 on 2023-04-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='basket',
            new_name='TblBasket',
        ),
    ]
